SELECT * FROM bookings;
SELECT * FROM cities;
SELECT * FROM hotels;
SELECT * FROM payment;
SELECT * FROM touristpackagebookings;
SELECT * FROM touristspots;
SELECT * FROM transportation;
SELECT * FROM travelagents;
SELECT * FROM users;